### PR TITLE
Add interviews from SourceSort

### PR DESCRIPTION
**Pull request by EmilePW**
Add interviews with Brian Carlson of node-postgres and Michael DeHaan of Ansible and SourceOptics about their experience of starting those respective projects and being maintainers.

### CODE REVIEW

**Comment by nayafia** [comment]
Great finds! Thanks @EmilePW! ✨

**Comment by EmilePW** [comment]
Thanks @nayafia and thanks for catching the typo. This is my site just to be clear, not sure if I should have mentioned that before.

**Comment by nayafia** [comment]
Oh awesome! Was trying to dig around and see who was behind it 😊Really cool to see a growing collection of interviews with open source developers.

**Comment by EmilePW** [comment]
@nayafia Much appreciated, and thank you for writing Roads and Bridges! That was one of the things that inspired me to start working on this.

**Pull request merged**
